version: "3.9"

services: 
  proxy:
    image: "mcproxy"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    networks:
      - "containers"
    privileged: true
    tty: true
    volumes:
      - "./plugins:/opt/proxy/plugins"
    container_name: "mcproxy"
    restart: "always"

networks:
  containers:
    external: true
